GET http://localhost:8000/api/products/list-create/ HTTP/1.1

###
PUT  http://localhost:8000/api/products/all/2/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNTc4OTE2LCJpYXQiOjE3NDM1Nzg2MTYsImp0aSI6ImE1NWQxODcxNDg0YzQxZTVhZmFhZTg0NmM0OWRlMzcyIiwidXNlcl9pZCI6Mn0.lXuHOlXj0YU3JHztrRaGZ4wLWqTvN-D6lAG-o2z2aDY

{
    "name": "A Scanner Darkly",
    "price": "21.99",
    "stock": 4,
    "description": "This is scanner."
}

###
POST http://localhost:8000/api/products/list-create/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNTc0OTc0LCJpYXQiOjE3NDM1NzQ2NzQsImp0aSI6IjQ5YmQ5MmJjM2UwMTQ4ZDk5MjdhY2FjNTZmNGUzM2Y5IiwidXNlcl9pZCI6Mn0.i43HIZbT5Yww0k-ZWO8mlI5ZnQbrojImyZLFlgMBv9w

{
    "name": "Xiaomi 15 Ultra",
    "price": "1000.05",
    "stock": 5,
    "description": "The DSLR Phone."
}

###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "radhamadhav"
}


###
GET http://localhost:8000/api/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNTc1ODE4LCJpYXQiOjE3NDM1NzU1MTgsImp0aSI6IjRhYmFlNTlkMTBiOTQyZTM4OTE3MjQ4MWE4NmRiYmJlIiwidXNlcl9pZCI6Mn0.c9ahTObao5uOiNBrzRQCkX9d8rSshcHcsDDMtVNrc3g


###
POST http://localhost:8000/api/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNzc3NDM0LCJpYXQiOjE3NDM3NzcxMzQsImp0aSI6IjgyYTczZjM3YjY5OTRhNmM4YTQ3ODllNGI3YmNjNTNjIiwidXNlcl9pZCI6MX0.8F0bOr-kebghEbm5NyCEni-fzrVbjFJWorCUJwsCuXw

{
    "status": "Pending",
    "items": [
        {
            "product": 4,
            "quantity": 1
        },
        {
            "product": 3,
            "quantity": 2
        }
    ]
}


###

PUT http://localhost:8000/api/orders/598dd455-c752-45e4-a01e-f8ad7d671a06/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQzNzc3NDM0LCJpYXQiOjE3NDM3NzcxMzQsImp0aSI6IjgyYTczZjM3YjY5OTRhNmM4YTQ3ODllNGI3YmNjNTNjIiwidXNlcl9pZCI6MX0.8F0bOr-kebghEbm5NyCEni-fzrVbjFJWorCUJwsCuXw

{
    "status": "Confirmed",
    "items": [
        {
            "product": 5,
            "quantity": 6
        },
        {
            "product": 3,
            "quantity": 2
        }
    ]
}